services:
  spring-app-blue:
    image: ${DOCKER_USERNAME}/cream:${IMAGE_TAG:-latest}
    container_name: cream-app-blue
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://${DB_HOST}:3306/${DATABASE_NAME}?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
      SPRING_DATASOURCE_USERNAME: ${DB_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      
      SPRING_DATA_REDIS_HOST: ${REDIS_HOST}
      SPRING_DATA_REDIS_PASSWORD: ${REDIS_PASSWORD}
      SPRING_DATA_REDIS_PORT: 6379
      
      PORTONE_STORE_ID: ${PORTONE_STORE_ID}
      PORTONE_API_SECRET: ${PORTONE_API_SECRET}
      PORTONE_CHANNELKEY: ${PORTONE_CHANNEL_KEY}
      
      SERVER_PORT: 8080
      JWT_SECRET: ${JWT_SECRET_KEY}
      AWS_ACCESS_KEY: ${AWS_ACCESS_KEY}
      AWS_SECRET_KEY: ${AWS_SECRET_KEY}
      BUCKET_NAME: ${BUCKET_NAME}
      AWS_REGION: ${AWS_REGION}
    ports:
      - "8081:8080"
    networks:
      - cream-network

  spring-app-green:
    image: ${DOCKER_USERNAME}/cream:${IMAGE_TAG:-latest}
    container_name: cream-app-green
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://${DB_HOST}:3306/${DATABASE_NAME}?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
      SPRING_DATASOURCE_USERNAME: ${DB_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}

      SPRING_DATA_REDIS_HOST: ${REDIS_HOST}
      SPRING_DATA_REDIS_PASSWORD: ${REDIS_PASSWORD}
      SPRING_DATA_REDIS_PORT: 6379

      PORTONE_STORE_ID: ${PORTONE_STORE_ID}
      PORTONE_API_SECRET: ${PORTONE_API_SECRET}
      PORTONE_CHANNELKEY: ${PORTONE_CHANNEL_KEY}

      SERVER_PORT: 8080
      JWT_SECRET: ${JWT_SECRET_KEY}
      AWS_ACCESS_KEY: ${AWS_ACCESS_KEY}
      AWS_SECRET_KEY: ${AWS_SECRET_KEY}
      BUCKET_NAME: ${BUCKET_NAME}
      AWS_REGION: ${AWS_REGION}
    ports:
      - "8082:8080"
    networks:
      - cream-network
