services:
  spring-app:
    image: ${DOCKER_USERNAME}/cream:${IMAGE_TAG:-latest}
    container_name: cream-app
    restart: always
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/${DATABASE_NAME}?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
      SPRING_DATASOURCE_USERNAME: ${DB_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      
      SPRING_DATA_REDIS_HOST: redis
      SPRING_DATA_REDIS_PORT: 6379
      SPRING_DATA_REDIS_PASSWORD: Sider

      PORTONE_STORE_ID: ${PORTONE_STORE_ID}
      PORTONE_API_SECRET: ${PORTONE_API_SECRET}
      PORTONE_CHANNELKEY: ${PORTONE_CHANNEL_KEY}
      
      SERVER_PORT: 8080
      JWT_SECRET: ${JWT_SECRET_KEY}
      AWS_ACCESS_KEY: ${AWS_ACCESS_KEY}
      AWS_SECRET_KEY: ${AWS_SECRET_KEY}
      BUCKET_NAME: ${BUCKET_NAME}
      AWS_REGION: ${AWS_REGION}
    ports:
      - "8080:8080"
    depends_on:
      - mysql
      - redis
    networks:
      - cream-network

  redis:
    image: redis:7-alpine
    container_name: redis
    restart: always
    networks:
      - cream-network

  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - cream-db-volume:/var/lib/mysql
    networks:
      - cream-network

volumes:
  cream-db-volume:

networks:
  cream-network:
    driver: bridge
